export const product = [
    {
      id: 1,
      img: "../src/Components/img/burger.jpg",
      price: 189,
      name:"Burger",
      alt: "buger",
    },
    {
        id: 2,
        img: "../src/Components/img/pizza.jpg",
        name:"pizza",
        price: 150,
        alt: "pizza",
      },
      {
        id: 3,
        img: "../src/Components/img/chikengravy.jpg",
        name:"chiken gravy",
        price: 150,
        alt: "chikengravy",
      },
      {
        id: 4,
        img: "../src/Components/img/appam.jpg",
        name:"appam",
        price: 40,
        alt: "appam",
      },
      {
        id: 5,
        img: "../src/Components/img/chapati.jpg",
        name:"chapati",
        price: 40,
        alt: "chapati",
      },
      {
        id: 6,
        img: "../src/Components/img/chickenpakoda.jpg",
        name:"chicken pakoda",
        price: 120,
        alt: "chickenpakoda",
      },
      {
        id: 7,
        img: "../src/Components/img/chiken65.jpg",
        name:"chiken 65",
        price: 130,
        alt: "chiken65",
      },
      {
        id: 8,
        img: "../src/Components/img/chikenbiriyani.jpg",
        name:"chiken biriyani",
        price: 200,
        alt: "chikenbiriyani",
      },
      {
        id: 9,
        img: "../src/Components/img/chikennoodles.jpg",
        name:"chiken noodles",
        price: 150,
        alt: "chikennoodles",
      },
      {
        id: 10,
        img: "../src/Components/img/chikennuglet.jpg",
        name:"chikennuglet",
        price: 190,
        alt: "chikennuglet",
      },
      {
        id: 11,
        img: "../src/Components/img/chikenwings.jpg",
        name:"chiken wings",
        price: 140,
        alt: "chikenwings",
      },
      {
        id: 12,
        img: "../src/Components/img/curdrice.jpg",
        name:"curd rice",
        price: 30,
        alt: "curdrice",
      },
      {
        id: 13,
        img: "../src/Components/img/fishfry.jpg",
        name:"fish fry",
        price: 150,
        alt: "fishfry",
      },
      {
        id: 14,
        img: "../src/Components/img/fishgravy.jpg",
        name:"fish gravy",
        price: 80,
        alt: "fishgravy",
      },

      {
        id: 15,
        img: "../src/Components/img/gril.jpg",
        name:"gril",
        price: 150,
        alt: "gril",
      },
      {
        id: 16,
        img: "../src/Components/img/honeychiken.jpg",
        name:"honey chiken",
        price: 160,
        alt: "honeychiken",   
       },
      {
        id: 17,
        img: "../src/Components/img/idiyappam.jpg",
        name:"idlyappam",
        price: 30,
        alt: "idlyappam",    
      },
      {
        id: 18,
        img: "../src/Components/img/idly.jpg",
        name:"idly",
        price: 30,
        alt: "idly",   
       },
      {
        id: 19,
        img: "../src/Components/img/lemonrice.jpg",
        name:"lemon rice",
        price: 30,
        alt: "lemonrice",   
       },
      {
        id: 20,
        img: "../src/Components/img/meals.jpg",
        name:"meals",
        price: 80,
        alt: "meals",   
       },
      {
        id: 21,
        img: "../src/Components/img/methuvada.jpg",
        name:"methuvada",
        price: 10,
        alt: "methuvada",   
       },
      {
        id: 22,
        img: "../src/Components/img/momos.jpg",
        name:"momos",
        price: 69,
        alt: "momos",   
       },
      {
        id: 23,
        img: "../src/Components/img/naan.jpg",
        name:"naan",
        price: 99,
        alt: "naan",   
       },
      {
        id: 24,
        img: "../src/Components/img/paniyaram.jpg",
        name:"paniyaram",
        price: 50,
        alt: "paniyaram",   
       },
      {
        id: 25,
        img: "../src/Components/img/parota.jpg",
        name:"parota",
        price: 35,
        alt: "parota",     
     },
      {
        id: 26,
        img: "../src/Components/img/podidosa.jpg",
        name:"podi dosa",
        price: 25,
        alt: "podidosa",  
        },
      {
        id: 27,
        img: "../src/Components/img/pongal.jpg",
        name:"pongal",
        price: 30,
        alt: "pongal",
      },
      {
        id: 28,
        img: "../src/Components/img/popcornchiken.jpg",
        name:"popcorn chiken",
        price: 139,
        alt: "popcornchiken",      
      },
      {
        id: 29,
        img: "../src/Components/img/puri.jpg",
        name:"puri",
        price: 20,
        alt: "puri",     
      },

      {
        id: 30,
        img: "../src/Components/img/ragiidly.jpg",
        name:"ragi idly",
        price: 40,
        alt: "ragiidly",   
       },
      {
        id: 31,
        img: "../src/Components/img/sambaricebiriyani.jpg",
        name:"sambarice biriyani",
        price: 230,
        alt: "sambaricebiriyani",
      },
      {
        id: 32,
        img: "../src/Components/img/tomotorice.jpg",
        name:"tomoto rice",
        price: 50,
        alt: "tomotorice",
      },
      {
        id: 33,
        img: "../src/Components/img/vada.jpg",
        name:"vada",
        price: 10,
        alt: "vada",
      },
      {
        id: 34,
        img: "../src/Components/img/vegpulov.jpg",
        name:"veg pulov",
        price: 60,
        alt: "vegpulov",
      },

  ];